import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'The terms that govern your use of Poisik.',
};

export default function TermsOfServicePage() {
  return (
    <main className="mx-auto max-w-3xl px-margin pt-32 pb-xxl">
      <h1 className="mb-md text-display-lg font-semibold text-text-primary">Terms of Service</h1>
      <p className="mb-xl text-label-md text-text-secondary">Last updated: July 25, 2026</p>

      <div className="space-y-xl text-body-md text-text-secondary">
        <section>
          <h2 className="mb-sm text-headline-md font-semibold text-text-primary">
            1. Using Poisik
          </h2>
          <p>
            By creating an account, you agree to use Poisik only for lawful purposes and only to
            analyze designs and content you own or have permission to submit. You are responsible
            for the content you upload.
          </p>
        </section>
        <section>
          <h2 className="mb-sm text-headline-md font-semibold text-text-primary">
            2. Plans and billing
          </h2>
          <p>
            Poisik offers a Free plan with a limited number of monthly analyses, and paid Pro and
            Team plans billed monthly through our payment provider. Upgrades, downgrades, and
            cancellations can be managed from your account settings at any time. Paid plans renew
            automatically until canceled.
          </p>
        </section>
        <section>
          <h2 className="mb-sm text-headline-md font-semibold text-text-primary">
            3. AI-generated analysis
          </h2>
          <p>
            Design critiques on Poisik are generated by AI models and are provided as guidance, not
            as a guarantee of design correctness, legal compliance, or accessibility certification.
            You remain responsible for reviewing and validating any changes made based on our
            recommendations.
          </p>
        </section>
        <section>
          <h2 className="mb-sm text-headline-md font-semibold text-text-primary">
            4. Acceptable use
          </h2>
          <p>
            You may not use Poisik to submit content that is illegal, infringing, or that you do not
            have the right to analyze. We reserve the right to suspend accounts that abuse the
            service, attempt to circumvent usage limits, or interfere with the platform&apos;s
            operation.
          </p>
        </section>
        <section>
          <h2 className="mb-sm text-headline-md font-semibold text-text-primary">
            5. Service availability
          </h2>
          <p>
            Poisik is provided on an &quot;as is&quot; basis. While we work to keep the service
            available and reliable, we do not guarantee uninterrupted access and are not liable for
            losses resulting from downtime or service interruptions.
          </p>
        </section>
        <section>
          <h2 className="mb-sm text-headline-md font-semibold text-text-primary">
            6. Changes to these terms
          </h2>
          <p>
            We may update these terms as the product evolves. Continued use of Poisik after an
            update constitutes acceptance of the revised terms.
          </p>
        </section>
      </div>
    </main>
  );
}
